config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'
  get 'admins/new'
  get 'admins/create'
  get 'admins/show'
  root 'items#index'

  devise_for :users

  resources :users do
    resources :your_cart_better_be_full, controller: :carts do
      resources :orders
    end
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :items do
    post 'search',  :on => :collection
  end


   # For the controller to be found, first declare the admins controller before namespace declaration
  resources :admins

  # Admin dashboard
  scope :admin do
    root to: "admins#index"
    resources :users
    resources :items
  end



  resources :items do
    resources :favorites
  end

  resources :users do
    resources :favorites
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_cart_item, dependent: :destroy
  has_many :items, through: :join_table_cart_item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :join_table_cart_item, dependent: :destroy
  has_many :carts, through: :join_table_cart_item

  has_many :join_table_order_items, dependent: :destroy
  has_many :carts, through: :join_table_order_items
  # TODO: allow minimum char for title to be eq. to 3
  validates :title,
  presence: true,
  length: { in: 4..30 }

  validates :description,
  presence: true,
  length: { in: 10..140 }

  validates :price,
  presence: true,
  numericality: { only_float: true, greater_than_or_equal_to: 0 }

  validates :image_url,
  presence: true

  has_many :favorites
  has_many :users, through: :favorites

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :join_table_order_items, dependent: :destroy
  has_many :items, through: :join_table_order_items

  after_create :order_send, :admin_order_send

  private
  def order_send
    UserMailer.order_email(self).deliver_now
  end

  def admin_order_send
    UserMailer.admin_order_email(self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :first_name, use: :slugged

  after_create :welcome_send
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	after_create :create_cart, :welcome_send

  has_many :favorites
  has_many :items, through: :favorites

  private
  def create_cart
  	Cart.create!(user_id: self.id)
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_user
	before_action :is_admin, only: [:index, :show]


	def index
	end

	def new
		@user = current_user
	end

	def create
		current_user.update_attribute :admin, true
		redirect_to admin_path(current_user.id)
	end

	def show
		@user = current_user
	end


	private
	def authenticate_user
		redirect_to root_path unless user_signed_in?
	end

	def is_admin
		current_user.admin?
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    
    if user_signed_in?
      @cart = User.find(current_user.id).cart
    else
      redirect_to root_path # Si le user tente d'accéder au panier sans sign in
    end

    @items = User.find(current_user.id).cart.items if @cart != nil # Si le panier est vide
  end

  def destroy
    @item = User.find(current_user.id).cart.items.find(params[:id])
    @cart = JoinTableCartItem.where(cart_id: current_user.cart).find_by(item_id: @item.id)
    @cart.destroy
    redirect_to user_carts_path(current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user, only: [:update, :destroy]

  def index
  	@items = Item.all
    @items = Item.where(breed: params[:breed]) if params[:breed] != nil
    @breed = params[:breed] if params[:breed] != nil

  end

  def show
    @item = Item.friendly.find_by(title: params[:id])
  end

  def search
    cleaned_search = params[:search].split.each { |word| word.capitalize! }.join(' ')
    @item = Item.friendly.find_by(title: cleaned_search)
  end

  def update
    @item = Item.friendly.find_by(title: params[:id])
    if user_signed_in?
      @cart = current_user.cart.id
      JoinTableCartItem.create!(cart_id: @cart, item_id: @item.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { }
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @item = User.find(current_user.id).cart.items.find(params[:id])
    @cart = JoinTableCartItem.where(cart_id: current_user.cart).find_by(item_id: @item.id)
    @cart.delete
    redirect_to user_your_cart_better_be_full_index_path(current_user.id)
  end

  def authenticate_user
    unless user_signed_in?
      flash[:danger] = "Please log in, or sign in."

    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate?, only: [:show]
  before_action :your_profile?, only: [:show]

  def show
    @user = User.friendly.find(params[:id])
  end

  private

  def authenticate?
    redirect_to root_path unless user_signed_in?
  end

  def your_profile?
    if current_user != User.friendly.find(params[:id])
      redirect_to root_path
    end
    # redirect_to root_path if current_user.is_admin != true &&
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def cart_count
    cart_items_count = User.find(current_user.id).cart.items.count 
    return cart_items_count
  end

  def already_favorite?(item)
    User.find(current_user.id).favorites.where(item_id: item).exists?
  end

  def focus_favorite(item)
    Favorite.where(item_id: item)
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/create.html.erb
<h1>Admins#create</h1>
<p>Find me in app/views/admins/create.html.erb</p>

app/views/admins/index.html.erb
<%= render 'layouts/colored_navbar' %>
<div class="jumbotron">
	<h1 class="display-3">Hello, <%= current_user.first_name %> </h1>
	<p class="lead">Welcome to your dashboard. </p>
	<hr class="my-4">

	<div class="container center-block mt-5">
		<ul class="list-group">

			<li class="list-group-item d-flex w-75 justify-content-between align-items-center">
				Number of users
				<span class="badge badge-primary badge-pill"><%= User.all.where(admin: false).count %></span>
			</li>

			<li class="list-group-item d-flex w-75 justify-content-between align-items-center">
				Number of orders
				<span class="badge badge-primary badge-pill"><% @total_orders = 0
				Order.all.each {|order| @total_orders +=1 if order.user.cart.items.count > 0}%>
				<%= @total_orders %></span>
			</li>
			<li class="list-group-item d-flex w-75 justify-content-between align-items-center">
				Average cart value
				<% @total_revenue = 0 %>
				<% Order.all.each do |order| %>
				<% order.items.each { |item| @total_revenue += item.price }%>
				<% end %>
				<span class="badge badge-primary badge-pill"> <%= @total_revenue/@total_orders %>€</span>
			</li>
			<li class="list-group-item d-flex w-75 justify-content-between align-items-center">
				Total Revenue 
				<span class="badge badge-primary badge-pill"><%= @total_revenue %>€</span>
			</li>


		</ul>
	</div>

</div>

app/views/admins/new.html.erb
<%= render 'layouts/colored_navbar' %>
<div class="card show-card">
  <h3 class="card-header">So you want to become a Chaton-Power admin ? </h3>
  <div class="card-body">
    <h5 class="card-title"> <%= @user.first_name %> <%= @user.last_name %> </h5>
    <h6 class="card-subtitle text-muted">Member since: <%= @user.created_at %></h6>
  </div>
  
  <div class="avatar-section">
    <div class="avatar-profile">
      <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, alt: 'avatar', :class => 'profile-img' %>
      <%= form_tag user_avatars_path(@user.id), multipart: true do %>
      <%= file_field_tag :avatar, :class =>"form-control-file", onchange: 'this.form.submit();' %>
      <% end %>
      <% else %>
      <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
      <%= form_tag user_avatars_path(@user.id), multipart: true do %>
      <%= file_field_tag :avatar, :class =>"form-control-file", onchange: 'this.form.submit();' %><br>
      <% end %>
      <% end %>
    </div>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item">Contact: <%= @user.email %></li>
  </ul>

  <div class="card-body">
    <%= link_to 'Edit my Profil', edit_user_registration_path, class: "card-link" %>
    <%= link_to 'Become an Admin! ', admins_path, method: :post,  class: "card-link" %>
  </div>


  <div class="card-footer text-muted">

  </div>

</div>
<div class="space">
  
</div>
<%= render "layouts/footer"%>

app/views/admins/show.html.erb
<%= render 'layouts/colored_navbar' %>
<div class="card show-card">
  <h3 class="card-header">So you want to become a Chaton-Power admin ? </h3>
  <div class="card-body">
    <h5 class="card-title"> <%= @user.first_name %> <%= @user.last_name %> </h5>
    <h6 class="card-subtitle text-muted">Member since: <%= @user.created_at %></h6>
  </div>
  
  <div class="avatar-section">
    <div class="avatar-profile">
      <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, alt: 'avatar', :class => 'profile-img' %>
      <%= form_tag user_avatars_path(@user.id), multipart: true do %>
      <%= file_field_tag :avatar, :class =>"form-control-file", onchange: 'this.form.submit();' %>
      <% end %>
      <% else %>
      <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
      <%= form_tag user_avatars_path(@user.id), multipart: true do %>
      <%= file_field_tag :avatar, :class =>"form-control-file", onchange: 'this.form.submit();' %><br>
      <% end %>
      <% end %>
    </div>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item">Contact: <%= @user.email %></li>
  </ul>

  <div class="card-body">
    <%= link_to 'Edit my Profil', edit_user_registration_path, class: "card-link" %>
  </div>

  <div class="card-body">
    <%= link_to 'Go to your admin dashboard ! ', admins_path, method: :get,  class: "card-link" %>
  </div>

  <div class="card-footer text-muted">

  </div>

</div>
<div class="space">
  
</div>
<%= render "layouts/footer"%>

app/views/charges/create.html.erb
<head>
	<meta HTTP-EQUIV="REFRESH" content="0; url='<%=root_path%>' ">
</head>
<h2>Thanks, you paid <strong><%= @amount %>€</strong>!</h2>

You will be automatically redirected to the main page in a few seconds...
If not, <a href="<%= root_path %>">click here</a>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%=@amount%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%=@amount * 100%>"
          data-locale="auto"></script>
<% end %>

app/views/layouts/_card.html.erb
<div class="card card-content mb-3">
  <h3 class="card-header" style="text-align: center;"> <%= @title %> </h3>
  <%= image_tag '1.jpeg' %>

	<div class="card-body" >

   	 <p class="card-text" style="float:left;"> <%= @price%> € </p> 
    	<%= link_to "Plus d'infos", item_path(@id), style: "float:right"%>

     	<%= link_to "", item_path(@id), method: 'put', class:"card-link, fas fa-shopping-cart caddie" %>
 	</div>
</div> 
<br/> <br/>

app/views/layouts/_colored_navbar.html.erb
<div id="navbar-up">
  <nav class="navbar navbar-expand-lg navbar-dark navbar-inner colored-navbar">
    <a class="navbar-brand" href="/"><img id="logo" src="http://www.icone-png.com/png/12/12497.png">
    </a> 

    <div class="form-inline">
      <%= form_tag(search_items_path, method: 'search') do %>
      <%= text_field_tag(:search, params[:search], class: "form-control") %>
      <%= submit_tag("Search", name: nil, class: "btn btn-secondary nav-button") %> 
      <% end %> 
    </div>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor01">
      <ul class="navbar-nav ml-auto">


        <% if user_signed_in? && !current_user.admin? %>
        <li class="nav-item">
          <%= link_to "Cart (#{cart_count})", user_your_cart_better_be_full_index_path(current_user.id), class: "nav-link colored-nav" %>
        </li>
        <li class="nav-item">
          <%= link_to "Favorites", user_favorites_path(current_user.id), class: "nav-link colored-nav" %>
        </li>
        <li class="nav-item">
          <%= link_to "Profile", user_path(current_user.id), class: "nav-link colored-nav" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, :class => "nav-link colored-nav", :method => :delete %>
        </li>
        <% elsif user_signed_in? && current_user.admin?%>
    <li class="nav-item">
        <%= link_to "Admin Dashboard", admins_index_path, class: "nav-link", :style => 'color:grey;' %>
      </li>
      <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, :class => "nav-link colored-nav", :method => :delete %>
        </li>
    <% else %>
    <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: "nav-link", 'data-toggle' => "modal", 'data-target' => "#modalSignup" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Log in', new_user_session_path, class: "nav-link", 'data-toggle' => "modal", 'data-target' => "#modalLogin" %>
    </li>
    <% end %>

      </ul>
    </div>
  </nav>
</div>
<br>

app/views/layouts/_footer.html.erb
<footer class="footer-distributed">

	<div class="footer-left">

		<h3>In Chaton power <span>we trust</span></h3>

		<p class="footer-links">
			<a href="https://github.com/CamilleRungette/">Camille</a>
			·
			<a href="https://github.com/ryanzidago">Ryan</a>
			·
			<a href="https://github.com/LKF92">Sylvain</a>
			·
			<a href="https://github.com/Ramoin">Romain</a>
			·
			<a href="https://github.com/vxnsteven">Steven</a>
		</p>

		<p class="footer-company-name">Chaton is love, Chaton is life  &copy; 2019</p>
		<br>
		<% if user_signed_in? && !current_user.admin? %>
		<p><%= link_to "Join us !", admins_new_path%></p>
		<% end %>
	</div>

	<div class="footer-center">

		<div>
			<i class="fa fa-map-marker"></i>
			<p>La Felicità<span>5 Parvis Alan Turing</span> 75013 Paris</p>
		</div>

		<div>
			<i class="fa fa-phone"></i>
			<p>+33 1 76 50 66 33</p>
		</div>

		<div>
			<i class="fa fa-envelope"></i>
			<p><a href="mailto:support@company.com">hello@chaton-power.io</a></p>
		</div>

	</div>

	<div class="footer-right">

		<p class="footer-company-about">
			<span>About the company</span>
			This tech company has been created by 5 incredible web developpers. We are increasingly passionate about technology, innovation and we define ourselves as early makers. With our diversity-empowering mindset, we are hunting for the new facebook. We lied. Thumb up if you fully read this.
		</p>

		<div class="footer-icons">

			<a href="https://github.com/CamilleRungette/ChatonPower"><i class="fab fa-facebook-f"></i></a>
			<a href="https://github.com/CamilleRungette/ChatonPower"><i class="fab fa-twitter"></i></a>
			<a href="https://github.com/CamilleRungette/ChatonPower"><i class="fab fa-linkedin-in"></i></a>
			<a href="https://github.com/CamilleRungette/ChatonPower"><i class="fab fa-github"></i></a>

		</div>

	</div>

</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-inner fixed-top">
  <a class="navbar-brand" href="/"><img id="logo" src="http://www.icone-png.com/png/12/12497.png">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? && !current_user.admin? %>
      <li class="nav-item">
        <%= link_to "Cart", user_your_cart_better_be_full_index_path, class: "nav-link" %>
      </li>
     <li class="nav-item">
      <%= link_to "Profile", user_your_cart_better_be_full_index_path(current_user), class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to "Log out", destroy_user_session_path, :class => "nav-link", :method => :delete %>
    </li>
    <% elsif user_signed_in? && current_user.admin?%>
    <li class="nav-item">
        <%= link_to "Admin Dashboard", admins_index_path, class: "nav-link", :style => 'color:grey;' %>
      </li>
      <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, :class => "nav-link colored-nav", :method => :delete %>
        </li>
    <% else %>
    <li class="nav-item">
      <%= link_to 'Sign up', new_user_registration_path, class: "nav-link", 'data-toggle' => "modal", 'data-target' => "#modalSignup" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Log in', new_user_session_path, class: "nav-link", 'data-toggle' => "modal", 'data-target' => "#modalLogin" %>
    </li>
    <% end %>
  </ul>
</div>
</nav>
  <br>

app/views/layouts/_transparent_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark navbar-inner fixed-top">
  <a class="navbar-brand" href="/"><img id="logo" src="http://www.icone-png.com/png/12/12497.png">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? && !current_user.admin?%>
      <li class="nav-item">
        <%= link_to "Cart (#{cart_count})", user_your_cart_better_be_full_index_path(current_user.id), class: "nav-link transparent-nav", id: "cart-count" %>
      </li>
      <li class="nav-item">
        <%= link_to "Favorites", user_favorites_path(current_user.id), class: "nav-link transparent-nav" %>
      </li>
      <li class="nav-item">
        <%= link_to "Profile", user_path(current_user.id), class: "nav-link transparent-nav" %>
      </li>
      <li class="nav-item">
        <%= link_to "Log out", destroy_user_session_path, :class => "nav-link transparent-nav", :method => :delete %>
      </li>
      <% elsif user_signed_in? && current_user.admin?%>
      <li class="nav-item">
        <%= link_to "Admin Dashboard", admins_index_path, class: "nav-link", :style => 'color:grey;' %>
      </li>
      <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, :class => "nav-link colored-nav", :method => :delete %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, class: "nav-link transparent-nav", 'data-toggle' => "modal", 'data-target' => "#modalSignup" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Log in', new_user_session_path, class: "nav-link transparent-nav", 'data-toggle' => "modal", 'data-target' => "#modalLogin" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ChatonPower</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<!-- Bootstrap CDN -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/minty/bootstrap.min.css" crossorigin="anonymous">
	
	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
	
	<%= stylesheet_link_tag 'application'%>
	<%= javascript_include_tag "application" %>
	<%= favicon_link_tag asset_path('cat-favicon.png') %>
	<meta name="viewport" content= "width=device-width, initial-scale=1.0"> 


</head>

<body>
	<div id="page-container">
		<%= render 'devise/registrations/new_registration' %>
		<%= render 'devise/sessions/new' %>
		<%= yield %>
		<br/>
	</div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</html>