config/routes.rb
Rails.application.routes.draw do
  get 'admins/index'
  get 'admins/new'
  get 'admins/create'
  get 'admins/show'
  root 'items#index'

  devise_for :users

  resources :users do
    resources :your_cart_better_be_full, controller: :carts do
      resources :orders
    end
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :items do
    post 'search',  :on => :collection
  end


   # For the controller to be found, first declare the admins controller before namespace declaration
  resources :admins

  # Admin dashboard
  scope :admin do
    root to: "admins#index"
    resources :users
    resources :items
  end



  resources :items do
    resources :favorites
  end

  resources :users do
    resources :favorites
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_cart_item, dependent: :destroy
  has_many :items, through: :join_table_cart_item
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  has_many :join_table_cart_item, dependent: :destroy
  has_many :carts, through: :join_table_cart_item

  has_many :join_table_order_items, dependent: :destroy
  has_many :carts, through: :join_table_order_items
  # TODO: allow minimum char for title to be eq. to 3
  validates :title,
  presence: true,
  length: { in: 4..30 }

  validates :description,
  presence: true,
  length: { in: 10..140 }

  validates :price,
  presence: true,
  numericality: { only_float: true, greater_than_or_equal_to: 0 }

  validates :image_url,
  presence: true

  has_many :favorites
  has_many :users, through: :favorites

end

app/models/join_table_cart_item.rb
class JoinTableCartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
end

app/models/join_table_order_item.rb
class JoinTableOrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :join_table_order_items, dependent: :destroy
  has_many :items, through: :join_table_order_items

  after_create :order_send, :admin_order_send

  private
  def order_send
    UserMailer.order_email(self).deliver_now
  end

  def admin_order_send
    UserMailer.admin_order_email(self).deliver_now
  end
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  friendly_id :first_name, use: :slugged

  after_create :welcome_send
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	after_create :create_cart, :welcome_send

  has_many :favorites
  has_many :items, through: :favorites

  private
  def create_cart
  	Cart.create!(user_id: self.id)
  end

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_user
	before_action :is_admin, only: [:index, :show]


	def index
	end

	def new
		@user = current_user
	end

	def create
		current_user.update_attribute :admin, true
		redirect_to admin_path(current_user.id)
	end

	def show
		@user = current_user
	end


	private
	def authenticate_user
		redirect_to root_path unless user_signed_in?
	end

	def is_admin
		current_user.admin?
	end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end

  def destroy
    @user = User.find(params[:user_id])
    @user.avatar.purge
    redirect_to(user_path(@user))
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @user = User.find(current_user.id)
    
    if user_signed_in?
      @cart = User.find(current_user.id).cart
    else
      redirect_to root_path # Si le user tente d'accéder au panier sans sign in
    end

    @items = User.find(current_user.id).cart.items if @cart != nil # Si le panier est vide
  end

  def destroy
    @item = User.find(current_user.id).cart.items.find(params[:id])
    @cart = JoinTableCartItem.where(cart_id: current_user.cart).find_by(item_id: @item.id)
    @cart.destroy
    redirect_to user_carts_path(current_user.id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :authenticate_user, only: [:update, :destroy]

  def index
  	@items = Item.all
    @items = Item.where(breed: params[:breed]) if params[:breed] != nil
    @breed = params[:breed] if params[:breed] != nil

  end

  def show
    @item = Item.friendly.find_by(title: params[:id])
  end

  def search
    cleaned_search = params[:search].split.each { |word| word.capitalize! }.join(' ')
    @item = Item.friendly.find_by(title: cleaned_search)
  end

  def update
    @item = Item.friendly.find_by(title: params[:id])
    if user_signed_in?
      @cart = current_user.cart.id
      JoinTableCartItem.create!(cart_id: @cart, item_id: @item.id)
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js { }
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    @item = User.find(current_user.id).cart.items.find(params[:id])
    @cart = JoinTableCartItem.where(cart_id: current_user.cart).find_by(item_id: @item.id)
    @cart.delete
    redirect_to user_your_cart_better_be_full_index_path(current_user.id)
  end

  def authenticate_user
    unless user_signed_in?
      flash[:danger] = "Please log in, or sign in."

    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def new
    @items = User.find(current_user.id).cart.items
    @amount = 0
    @items.each do |item|
      @amount += item.price
    end
  end

  def create
    @items = User.find(current_user.id).cart.items
    @amount = 0
    @items.each do |item|
      @amount += item.price
    end

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: (@amount.to_i)*100,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })
  redirect_to user_your_cart_better_be_full_order_path(current_user.id, current_user.cart.id, current_user.id)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

  def show
    @user = current_user
    @cart = current_user.cart
    @order = Order.create(user_id: current_user.id)
    @cart.items.each do |item|
      JoinTableOrderItem.create!(
        order_id: @order.id,
        item_id: item.id
      )
    end

    @cart.items.clear
    @total = Array.new
    @order.items.each do |item|
      @total << item.price
    end
    @total = @total.inject(:+)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate?, only: [:show]
  before_action :your_profile?, only: [:show]

  def show
    @user = User.friendly.find(params[:id])
  end

  private

  def authenticate?
    redirect_to root_path unless user_signed_in?
  end

  def your_profile?
    if current_user != User.friendly.find(params[:id])
      redirect_to root_path
    end
    # redirect_to root_path if current_user.is_admin != true &&
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def cart_count
    cart_items_count = User.find(current_user.id).cart.items.count 
    return cart_items_count
  end

  def already_favorite?(item)
    User.find(current_user.id).favorites.where(item_id: item).exists?
  end

  def focus_favorite(item)
    Favorite.where(item_id: item)
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/custom_failure_helper.rb
module CustomFailureHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/index.html.erb
<%= render "layouts/colored_navbar" %>
<% if @cart == nil || @items.length == 0 %>

<div class="list-group-item" id="empty-cart">
	<img src="https://risibank.fr/cache/stickers/d123/12382-full.png" id="denis-ah">
	<h2 class="text-center">Your cart is empty!</h2>
	<p class="text-center"><audio src="https://www.cjoint.com/doc/17_04/GDBo22CpPLB_Denis-Brogniart-AH.mp3" autoplay="true"></audio></p>
	<p class="text-center"><%= link_to "Back home", root_path %></p>
</div>

<% else %>

<h1 class="index-title"> Your cart:</h1>

<ul class="list-group-cart">
	<% @items.each do |item| %>
	<li class="list-group-item d-flex justify-content-between align-items-center list-checkout-cart">

		<div class="item-details-container">
			<%= image_tag "#{item.image_url}", alt: "Card image", class: "product-image" %>
			<div class="item-title-description">
				<h3><%= link_to item.title, item_path(item.title)%></h3>
				<small class="text-muted description-text-item">Lorem ipsum dolor sit amet, consectetur adipiscing elit. In at quam placerat, aliquet ex et, rhoncus erat. Pellentesque faucibus semper magna, id blandit enim eleifend egestas. Duis iaculis ut est in pulvinar.</small>
			</div>

		<div class="price-container">
			<%= item.price %>€
		</div>

		<div class="quantity-button">
			<div class="form-group">
				<label for="exampleSelect1">Quantity: </label>
				<div class="inputndelete">
					<div>
						<select class="form-control" id="exampleSelect1">
							<option>1</option>
							<option>2</option>
							<option>3</option>
							<option>4</option>
							<option>5</option>
						</select>
					</div>

					<div class="trash-div">
						<%= link_to "", item_path(item.id), method: :delete, :class => "fas fa-trash-alt" %>
					</div>
				</div>
			</div>
		</div>
		</li>
		<% end %>
	</ul>

	<div class="total">
		<% count = 0.0 %>
		<% @items.each do |item|%>
		<% count += item.price %>
		<% end %>

		<hr class="total-bar" >
		<h5 class="total-cart">Sous-total (<%= @items.count %> articles) : <span class="price-color"><%= count%>€</span></h5>
		<%= link_to "Checkout", new_user_your_cart_better_be_full_order_path(current_user.id, current_user.cart.id), class: "btn btn-outline-primary total-cart", id: "checkout-button" %>
	</div>
<% end %>

<div class="space">
</div>

<%= render "layouts/footer"%>

app/views/items/_card.html.erb
<div class="card card-content mb-3">
	<h3 class="card-header" style="text-align: center;">
		<%= @title %>
		<% if user_signed_in? && already_favorite?(@id) != true %>
		<%= link_to "", item_favorites_path(@id), remote: true, method: 'post', class:"card-link far fa-star", id:"favorite#{@id}" %>
		<% elsif user_signed_in? && already_favorite?(@id) == true %>
		<%= link_to "", item_favorite_path(@id, focus_favorite(@id)), remote: true, method: 'delete', class:"card-link fas fa-star", id:"favorite#{@id}" %>
		<% end %>
	</h3>
	<%= image_tag "#{@image_url}", alt: "Card image", class: "cat-picture" %>
	<div class="card-body" >
		<p class="card-text" style="float:left;"> <%= @price%> € </p>
		<%= link_to "See more", item_path(@title), style: "float:right"%>
			<% if user_signed_in? %>
				<%= link_to "", item_path(@title), method: 'put', class:"card-link, fas fa-shopping-cart caddie", remote: true %>
			<% else %>
				<%= link_to '', new_user_session_path, class: "card-link, fas fa-shopping-cart caddie", 'data-toggle' => "modal", 'data-target' => "#modalLogin" %>
			<% end %>
	</div>
</div>
<br/> <br/>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<%= render 'layouts/transparent_navbar' %>

<div class="video-container">
	<div class="banner">
	<%= video_tag "cat.mp4", controls: false, autoplay: true, muted: true, loop: true, id: "home-video", class:"video" %>
	</div>
</div>

<div class="banner-text">
	<div class="typing">
		<h1 class="title-banner">CHATON POWER.</h1>
	</div>
	<br/>

	<p class="text-banner">You love cats? Us too. Welcome to paradise. <br/><a class="btn btn-secondary" href="#section2" id="scroll-button">See our pictures </a>
	</p>
</div>

<div class="space">
</div> <br/><br/><br/><br/>

<div id="section2">
</div>

<div class="cat-cards">
	<br/><br/>
	<% if @breed == nil %>
	<h1 class="index-title"> Pick you favorite</h1>
	<% else %>
	<h1 class="index-title">Our <%= @breed %> cats!</h1>
	<% end %>
	<div class="search-bar">
		<%= form_tag(search_items_path, method: 'search', class: "search-form") do %>
		<%= text_field_tag(:search, params[:search], class: "pl-3 form-control search") %>
		<%= submit_tag("Search", name: nil, class: "btn btn-primary search-button") %>
		<% end %>
	</div>
	<br/>

	<div class="flex-container">
		<% @items.each do |item| %>
		<% @title = item.title %>
		<% @price = item.price %>
		<% @image_url = item.image_url %>
		<% @id = item.id %>
		<div>
			<%= render "card" %>
		</div> <br/> <br/>
		<% end %>

	</div>
<%= render "layouts/footer"%>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<%= render "layouts/colored_navbar" %>
<div id="section1">

  <div class="card show-card">
    <h3 class="card-header"><%= @item.title %></h3>

    <div class="card-body">
      <h5 class="card-title"> &copy <%= Faker::Name.name  %></h5>
      <h6 class="card-subtitle text-muted">Photographer</h6>
    </div>

    <%= image_tag "#{rand(1..10)}.jpeg", alt: "Card image", class: "show-img" %>
    <div class="card-body">
      <p class="card-text"><%= @item.description %></p>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item"> <%= @item.price %> €</li>
      <li class="list-group-item">120 x 90 cm</li>
    </ul>
    <div class="card-body">
      <a href="/" class="card-link">Home Page</a>
      <%= link_to "Add to cart", item_path(@item.title), method: 'put', class:"card-link" %>
    </div>
    
    <div class="card-footer text-muted">
      2 days ago
    </div>
  </div>
</div>

<div class="space"> 
</div>
<%= render 'layouts/footer' %>

app/views/items/show.html.erb
<body class="show-page">
<%= render "layouts/colored_navbar" %>

  <div class="card show-card">
    <h3 class="card-header"><%= @item.title %></h3>
    <div class="card-body">
      <h5 class="card-title"> &copy <%= Faker::Name.name  %></h5>
      <h6 class="card-subtitle text-muted">Photographer</h6>
    </div>
    <%= image_tag "#{@item.image_url}", alt: "Card image", class: "show-img" %>
    <div class="card-body">
      <p class="card-text">
          Breed: <%= link_to @item.breed, items_path(breed: @item.breed) %> <br/>

        <%= @item.description %>
      </p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item"> <%= @item.price %> €</li>
      <li class="list-group-item">120 x 90 cm</li>
    </ul>
    <div class="card-body">
      <a href="/" class="card-link">Home Page</a>

      <%= link_to "Add to cart", item_path(@item.title), method: 'put', class:"card-link" %>

    </div>

    <div class="card-footer text-muted">
      2 days ago
    </div>
  </div>

  <div class="space"></div>

<%= render 'layouts/footer' %>

</body>

app/views/items/update.js.erb
document.querySelector("#cart-count").innerHTML = "Cart (<%= cart_count %>)";

app/views/orders/create.html.erb
<head>
	<meta HTTP-EQUIV="REFRESH" content="5; url='<%=root_path%>' ">
</head>
<body>
<h2>Thanks, you paid <strong><%= @amount %>€</strong>!</h2>

	You will be automatically redirected to the main page in a few seconds...
If not, <a href="<%= root_path %>">click here</a>
</body>

app/views/orders/new.html.erb
<body class="stripe-body">
<%= render "layouts/colored_navbar" %>

  <div class="main-stripe">
    <div class="container-stripe">

      <%= form_tag user_your_cart_better_be_full_orders_path(current_user.id, current_user.cart.id) do %>

        <article>
          <% if flash[:error].present? %>
            <div id="error_explanation">
              <p><%= flash[:error] %></p>
            </div>
          <% end %>
            <h1 class="display-3"> Checking out: </h1> <br/> <br/>
            
          <label class="amount">
            <span>Amount: <%=@amount%></span>
          </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="Your cat picture order"
        data-amount="<%=@amount * 100%>"
        data-locale="auto"></script> <br/>

        <%= image_tag "pusheen.png", alt: "Pusheen", class: "stripe-logo" %>

    <% end %>

    </div>
  </div>
</body>

app/views/orders/show.html.erb
<meta HTTP-EQUIV="REFRESH" content="6; url=<%=root_path%>">
  <div class="jumbotron">
    <h1 class="display-3">Meeeeooow!</h1>
      <p class="lead">The Chaton-Power team thanks you for your order ! !</p>
      <hr class="my-4">
        <% @order.items.each do |item| %>
          <p><%= item.title %> : <%= item.price %></p>
        <% end %></p>
      <p><em> Total: <%= @total %> € </em></p>
    <p class="lead">
      <p>You will be automatically redirected in a few seconds...</p>
        <p>If not, click below</p>
      <a class="btn btn-primary btn-sm" href="<%=root_path%>" role="button">Cat Gallery</a>
    </p>
  </div>
<%= yield %>

app/views/users/edit.html.erb
<%= render "devise/registrations/edit" %>

app/views/users/show.html.erb
<body class="show-page">

<%= render 'layouts/colored_navbar' %>

<div class="card show-card">
  <h3 class="card-header">Welcome to you profile:</h3>

    <div class="card-body">
      <h5 class="card-title"> <%= @user.first_name %> <%= @user.last_name %> </h5>
      <h6 class="card-subtitle text-muted">Member since: <%= @user.created_at %></h6>
    </div>

  <div class="avatar-section">
    <div class="avatar-profile">
      <% if @user.avatar.attached? %>
        <%= image_tag @user.avatar, alt: 'avatar', :class => 'profile-img' %>
          <%= form_tag user_avatars_path(@user.id), multipart: true do %> <br/>
          <%= file_field_tag :avatar, :class =>"form-control-file choose", onchange: 'this.form.submit();' %>
          <% end %>
      <% else %>
      <p class="avatar-profile">=== You don't have an avatar yet ===</p> <br/>
          <%= form_tag user_avatars_path(@user.id), multipart: true do %>
          <%= file_field_tag :avatar, :class =>"form-control-file", onchange: 'this.form.submit();' %><br>
          <% end %>
      <% end %>
    </div>
  </div>

    <div class="card-body">
      <p class="card-text"></p>
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item"> Number of orders : <%= current_user.orders.count %>
      </li>
    <li class="list-group-item">Contact: <%= @user.email %></li>
    </ul>
    <div class="card-body">
      <%= link_to 'Home', root_path, class: "card-link" %>
      <%= link_to 'Edit', edit_user_registration_path, class: "card-link" %>
    </div>
</div>

<div class="space">
</div>

<%= render "layouts/footer"%>
</body>